---
# example playbook for module 'irmc_ldap'
# to manage iRMC LDAP settings

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: irmc_ldap - usage examples
  connection: local
  hosts: iRMC_group

  vars:
    # iRMC login credentials
    # irmc_user: "admin"
    # irmc_password: "admin"
    # Note: set validate_certificate to false for self-signed certificate
    # validate_certificate: false

  gather_facts: no

  tasks:
    # Get LDAP data
    - name: Get LDAP data
      irmc_ldap:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "get"
      register: ldap
      delegate_to: localhost
    - name: Show iRMC LDAP data
      debug:
        msg: "{{ ldap.ldap }}"
    
    # Set LDAP data
    - name: Set LDAP data
      irmc_ldap:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "set"
        ldap_user: "username"
        ldap_password: "password"
      delegate_to: localhost

