---
# example playbook for module 'irmc_connectvm'
# to connect iRMC Virtual Media Data

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: irmc_connectvm - usage examples
  connection: local
  hosts: iRMC_group

  vars:
    # iRMC login credentials
    # irmc_user: "admin"
    # irmc_password: "admin"
    # Note: set validate_certificate to false for self-signed certificate
    # validate_certificate: false

  gather_facts: no

  tasks:
    # Disconnect Virtual CD
    - name: Disconnect Virtual CD
      irmc_connectvm:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "DisconnectCD"
      delegate_to: localhost
    
    # Connect Virtual CD
    - name: Connect Virtual CD
      irmc_connectvm:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "ConnectCD"
      delegate_to: localhost

